### ISSUE TITLE
Curve connector

### ISSUE THREAD

**Issue by fengtality** [hummingbot/gateway#101]
**Description**
* A connector to Curve (https://curve.fi/)
* Should implement the `Uniswapish` class
* Support `ethereum`, `avalanche` and `polygon` chains
* Contains unit tests and meets % coverage requirements

See existing work: https://github.com/hummingbot/hummingbot/pull/5334

**Bounty**
* Sponsor: Hummingbot Foundation
* Bounty Amount: 286,500 HBOT
* Developer Payment: 286,500 HBOT (100%)
* Proposal: https://snapshot.org/#/hbot-ip.eth/proposal/0x0f86d963fc90c972efb78f6ae56b2ae2b189c6d6c8ffa1470aa000251a1163cb
* Status: Open

**Comment by adamjbradley** [comment]
Is this taken? Interested...

**Comment by fengtality** [comment]
> Is this taken? Interested...

No, it's still open.

**Comment by fengtality** [comment]
Can you share what you've built for Balancer connector with me so that I
can assess your code before we assign you a bounty?

**Comment by fengtality** [comment]
This bounty remains open. 

If you are a new dev who hasn't picked up any bounties before, please send me sample code if you want to be assigned this bounty, as it's a larger, more complex one.

**Comment by aaronansc** [comment]
Its July 15th is this still viable to participate? I can see quite a bit has been worked on in the repo

**Comment by fengtality** [comment]
> Its July 15th is this still viable to participate? I can see quite a bit has been worked on in the repo

Yes, the task is to take over the existing work and finish it off. If you'd like to take this bounty, please book a time on my calendar for a brief screening call: https://calendly.com/hummingbot/michael-feng

**Comment by nikspz** [comment]
Assigned to @vic-en, please be informed:

- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by vic-en** [comment]
@nikspz Wrapping up and about to commence testing.
ETA end of week.

**Comment by nikspz** [comment]
PR #215 Merged to latest development branch (dev-1.22.0), connector will be available in 1.22.0 Release

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @vic-en . The connector has been deployed on development branch and next hummingbot version 1.22.0
