### ISSUE TITLE
Interact directly with the pool in Uniswap connector 

### ISSUE THREAD

**Issue by fengtality** [hummingbot/gateway#112]
**Description**

* Users have reported that the Uniswap connector is slow compared to other connectors as well as other bots, resulting in missed arbitrage opportunities
* This may be due to the fact that it uses the [smart order router](https://docs.uniswap.org/sdk/v3/guides/routing) to estimate and execute trades, rather than [getting a quote](https://docs.uniswap.org/sdk/v3/overview) and [executing a trade](https://docs.uniswap.org/sdk/v3/guides/trading)
* Add the ability to use these direct methods rather than the router to the Uniswap connector as an option
* Afterwards, `estimateSellTrade`, `estimateBuyTrade`, and `executeTrade` should be able to use the quote/trade methodology described in the Uniswap docs, but also the existing router method
* The following variables to the Uniswap connector config should be added:
  * `useRouter` (bool): if True, estimation and execution functions use router; if false, use quote and trade functions of SDK; 
  * `feeTier` (string): Matches one of the Uniswap fee tier strings. If useRouter is False, then user has to specify `feeTier` to find the right pool
* Add these new variables to the Uniswap default config template. By default, `useRouter` should be True, and `feeTier` is "MEDIUM"

**Bounty**

* Sponsor: Hummingbot Foundation
* Bounty Type: Enhancement / Open Source
* Bounty Amount: 100,000 HBOT (P1)
* Developer Payment: 100,000 HBOT (100%)
* Status: Open

**Comment by zedquach** [comment]
What is the expected timeline for this ticket?

**Comment by fengtality** [comment]
> What is the expected timeline for this ticket?

Do you mean when it'll be delivered? That depends on if/when a community dev picks up this bounty.

**Comment by VPashkov** [comment]
@fengtality I would like to take a shot at this. I have a few questions, though.
1. How `useRouter` and `feeTier` will be configured? Should I simply provide public getters/setters, add parameters to constructor/getInstance methods, read it from config, or something else?
2. I will need to store Quoter and Pool factory contract addresses somewhere. Should I extend [UniswapConfig](https://github.com/hummingbot/gateway/blob/80f7ea8735544fadbed8d4ea878b0f478cacdec5/src/connectors/uniswap/uniswap.config.ts#L25)? If yes, I will need also to update its [schema](https://github.com/hummingbot/gateway/blob/80f7ea8735544fadbed8d4ea878b0f478cacdec5/src/services/schema/uniswap-schema.json), [templates](https://github.com/hummingbot/gateway/blob/80f7ea8735544fadbed8d4ea878b0f478cacdec5/src/templates/uniswap.yml), etc., right?
3. At first glance `executeTrade`, should just work after updating `estimateSellTrade` and `estimateBuyTrade`. Do you have something specific in mind that needs to be done with it or do I simply need to make sure it works with the quote/trade methodology?

**Comment by zedquach** [comment]
I'll take this

**Comment by fengtality** [comment]
@VPashkov Thanks - see below for answers to your questions. If you would like to be assigned this issue, you have first dibs. @zedquach we will let you know if it's open in a few days.

- I recommend this approach, which should be simplest - if it's not clear, I can provide more guidance.
- `useRouter` and `feeTier` are 2 additional params in [[UniswapConfig](https://github.com/hummingbot/gateway/blob/80f7ea8735544fadbed8d4ea878b0f478cacdec5/src/connectors/uniswap/uniswap.config.ts)](https://github.com/hummingbot/gateway/blob/80f7ea8735544fadbed8d4ea878b0f478cacdec5/src/connectors/uniswap/uniswap.config.ts). You can store the Quoter and Pool factory contract addresses here too.
- In the future, we should provide more flexibility on a request-by-request basis, but this approach should limit scope of this task and not necessitate changes to Hummingbot client
- Update the Uniswap [[schema](https://github.com/hummingbot/gateway/blob/80f7ea8735544fadbed8d4ea878b0f478cacdec5/src/services/schema/uniswap-schema.json)](https://github.com/hummingbot/gateway/blob/80f7ea8735544fadbed8d4ea878b0f478cacdec5/src/services/schema/uniswap-schema.json) and templates accordingly. You can make all the new params optional.
- In [[Uniswap](https://github.com/hummingbot/gateway/blob/80f7ea8735544fadbed8d4ea878b0f478cacdec5/src/connectors/uniswap/uniswap.ts)](https://github.com/hummingbot/gateway/blob/80f7ea8735544fadbed8d4ea878b0f478cacdec5/src/connectors/uniswap/uniswap.ts), read these values and modify `estimateSellTrade` and `estimateBuyTrade` so that it gets a quote from the pool directly following [[the guide](https://docs.uniswap.org/sdk/v3/guides/trading)](https://docs.uniswap.org/sdk/v3/guides/trading)
- Object returned should remain the same `{ trade: route.trade, expectedAmount };`
- I believe no changes should be needed to `executeTrade` nor the controllers and validators

**Comment by VPashkov** [comment]
@fengtality Yes, I would like to be assigned. I think I got all the answers I need for now. Thanks.

**Comment by VPashkov** [comment]
A quick status update.
I have a working implementation. It works significantly faster. 
Some naive performance testing shows 250-350ms for price requests(`/amm/price`) for new implementation versus 3.5-7 seconds for the old one. For trade requests(`/amm/trade`) it's 2-2.5 seconds versus 7-9 seconds.
I'm working on unit tests right now.

**Comment by fengtality** [comment]
wow that's amazing! looking forward to playing with it!

**Comment by nikspz** [comment]
hi @VPashkov Could you please add your updates here and submit PR/draft?

**Comment by VPashkov** [comment]
Hi @nikspz.
Sorry for the delay. I'm struggling with writing tests for the `executeTrade` method. A lot of mocking is required, but I think it needs to be done to make sure I'm not breaking existing code. I think I will need a couple of more days to finish.

**Comment by fengtality** [comment]
Hey @VPashkov if you're having issues mocking data for tests, I suggest submitting the PR as-is. 

We are aware of the challenges testing Gateway functions that require network calls and don't want to make devs spend time unnecessarily

**Comment by VPashkov** [comment]
Got it. I'm sending PR without tests for `executeTrade` then.

**Comment by toxicehc** [comment]
Hi @VPashkov - Would this also work on polygon uniswap?

**Comment by nikspz** [comment]
@VPashkov Could you please fill up & submit the AML Policy Form via this link: https://forms.gle/ZeSRvWUU3gBeHPbH6
This is a one-time process for each ETH Address used to receive HBOT bounty.

**Comment by toxicehc** [comment]
@VPashkov - check my DM on discord also please.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by VPashkov** [comment]
Hey @toxicehc, sorry didn't see your message. I'll check DM on Discord. Thanks.
