### ISSUE TITLE
POST price and POST trade not working for specific pair on Pancakeswap 

### ISSUE THREAD

**Issue by Joakim6** [hummingbot/gateway#117]
**Describe the bug**
When I call POST /amm/price for the token pair USDT-HYPC, I get the following error:

Error: Price query failed: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] 

However, the same request for the WBNB-HYPC pair works just fine.

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):

1. First add HYPC to the pancakeswap token list.
name: Hypercycle
symbol: HYPC
address: 0x7881cD2B5724431372F57C50E91611352557A606
nr of decimals: 6

Note the number of decimals being lower than usual.

(By the way, I did not find an image to use, so I just used the image of a random other token in the list - this shouldn't be a problem right?)

see also the contract address here: https://bscscan.com/token/0x7881cd2b5724431372f57c50e91611352557a606

2. Approve HYPC for trading on pancakeswap.

3. in Postman, run POST amm/price for the WBNB-HYPC pair, just to ensure that this one is working just fine.
 
4. Then do the same for the USDT-HYPC pair. This is where I get the error.
...

**Screenshots**
Screenshots added of postman results.
![Screenshot from 2023-05-30 15-43-38](https://github.com/hummingbot/gateway/assets/89662393/91184531-a069-4f14-b606-ebbf77e2423c)
![Screenshot from 2023-05-30 15-44-03](https://github.com/hummingbot/gateway/assets/89662393/031a10b4-62ab-4c44-854a-6721478267d9)
![Screenshot from 2023-05-30 15-44-17](https://github.com/hummingbot/gateway/assets/89662393/12ecd6f6-ef2e-4677-966f-8de166e26c84)

**Release version**
I did not use hummingbot for this but for what it's worth my version is 1.15.0.

**Attachments**
Attached the chain.yml file, as well as the token list I used.
[chainyml file and bep20 token list.zip](https://github.com/hummingbot/gateway/files/11600685/chainyml.file.and.bep20.token.list.zip)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
BlueFish#5562

**Comment by fengtality** [comment]
This isn't a bug since I don't think a USDT/HYPC pool exists on PancakeSwap whereas a WBNB/HYPC pool does.
