### ISSUE TITLE
Gateway logs not recorded using `docker-gateway`

### ISSUE THREAD

**Issue by nikspz** [hummingbot/gateway#12]
the issue on logging docker-gateway

`gateway logs not recorded` in gateway_files/gateway_logs 
using `docker-gateway`

Steps: 

1. Clone and install hummingbot using development branch
2. Gateway generate_certs
3. Set up gateway docker with ./create-gateway.sh
4. Create/ Run amm_arb strategy
5. Review gateway_files/logs

Actual:
No logs recorded for docker-gateway 

Expected:
Gateway logs recorded, user could access to Gateway logs records

**Comment by nikspz** [comment]
Upon checking no logs also for docker-gateway using docker-client

Steps:

Clone and install docker hummingbot client using development branch
Gateway generate_certs
Set up gateway docker with ./create-gateway.sh
Create/ Run amm_arb strategy
Review gateway_files/logs
Actual:
No logs recorded for docker-gateway

Expected:
Gateway logs recorded, user could access to Gateway logs records

**Comment by fengtality** [comment]
@nikspz I tried to reproduce and saw that my `gateway_files/logs` on MacOS showed output as soon as the Gateway server started:

```
2023-02-15 11:18:32 | info | 	⚡️ Starting Gateway API on port 15888... | undefined
2023-02-15 11:18:32 | info | 	The gateway server is secured behind HTTPS. | undefined
2023-02-15 11:18:32 | info | 	⚡️ Swagger listening on port 8080. Read the Gateway API documentation at 127.0.0.1:8080 | undefined
```

Can you try it on the latest `development` and record a Loom that shows what you're seeing if you are still encountering this issue?

**Comment by nikspz** [comment]
@fengtality I used Ubuntu 20.04
gateway latest tag + client source latest development
https://www.loom.com/share/53e174e43bfe4f938e1eb958ed7cb778

Latest dev commit:
![image](https://user-images.githubusercontent.com/83953535/218983919-7ca5de92-0769-4fab-a019-1d1578ac8c35.png)

latest
![image](https://user-images.githubusercontent.com/83953535/218984025-8a744248-04bd-41ce-913c-0f3ed9fad928.png)

Same for the gateway `development` tag + client source latest development
https://www.loom.com/share/c31b3783e4414ea195b39b5045ec772b

**Comment by rapcmia** [comment]
Issue related to folder permission for Ubuntu based. Logs are created once permission is modified. All ok now
