### ISSUE TITLE
Docker - Unhandled error in background tasks due to no such file or directory 

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/gateway#145]
**Describe the bug**
When setting up docker using [bash scripts](https://github.com/hummingbot/deploy-examples/tree/main/bash_scripts) `gateway-create.sh` and selected `{N, no}`on the prompt `Do you want to generate default token lists? [Y/N]` it will still successfully create a docker gateway container and  wont copy any to the `conf/list/...` folder resulting on the below screenshot error when connecting to any of hummingbot's DEX connector which is expected due to `no such file or directory`

![image](https://github.com/hummingbot/gateway/assets/73840223/c92a2363-f836-44fe-a545-ce746cefb6f4)

Sample screenshot of `tokenListSource`
![image](https://github.com/hummingbot/gateway/assets/73840223/0ad9d5c9-8d06-439d-9cdb-b441ac234026)

While this is true that there is an error, a user should be able to fix this by:
1. Stop and delete the gateway docker container (sample container: gw1), `docker stop gw1 && docker rm gw1`
2. Run the `gateway-create.sh` script again and this time make sure to select `Y` on  prompt `Do you want to generate default token lists? [Y/N]` 👀 

**Steps To Reproduce**
- Run `gateway-create.sh`
- Enter Gateway version you want to use [latest/latest-arm] ✅
- Enter a name for your new Gateway instance (default = "gateway") ✅
- Enter the folder name where your Gateway files will be saved (default = "xxx_files") ✅
- Enter the passphrase you used to generate certificates in Hummingbot ✅
- Do you want to proceed with installation? `Y`
    - Created gateway successfully
    - Do you want to generate certs from a Hummingbot instance? `Y` ✅
    - Enter the path to the folder where Hummingbot certificates are stored ✅
    - Do you want to generate default token lists? [Y/N] `select N or press enter`
- Go back to client and setup connector

**Release version**
N/A, issue related to Deploy example's [bash scripts](https://github.com/hummingbot/deploy-examples/tree/main/bash_scripts) which is related to `gateway` setup

**Comment by fengtality** [comment]
## Bounty

* Sponsor: Hummingbot Foundation
* Budget: [HGP-26](https://snapshot.org/#/hbot.eth/proposal/0x7a02f532e0452d3ce7f8b64a8a52e6bed285cc65461a1523fa0f91f2024f8c01)
* Classification: P3
* Bounty: 10,000 HBOT
* Developer share: 100% - paid upon merge to development
* Status: OPEN

**Comment by isreallee82** [comment]
Is this still available I would like to work on this

**Comment by nikspz** [comment]
Assigned to @isreallee82, please be informed:

- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by isreallee82** [comment]
Alright 😊 Thanks

**Comment by isreallee82** [comment]
Run gateway-create.sh
Enter Gateway version you want to use [latest/latest-arm] ✅
Enter a name for your new Gateway instance (default = "gateway") ✅
Enter the folder name where your Gateway files will be saved (default = "xxx_files") ✅
Enter the passphrase you used to generate certificates in Hummingbot ✅
Do you want to proceed with installation? Y
Created gateway successfully
Do you want to generate certs from a Hummingbot instance? Y ✅
Enter the path to the folder where Hummingbot certificates are stored ✅
Do you want to generate default token lists? [Y/N] select N or press enter

on going back to client and setup connector I got no error plus the folder conf/lists still generates



![Image](https://github.com/hummingbot/gateway/assets/70828114/88f8170b-1783-4a2c-a48a-055e3d010597)
![Image](https://github.com/hummingbot/gateway/assets/70828114/45197448-3464-4cc5-9322-21edfe40b6e9)
![Image](https://github.com/hummingbot/gateway/assets/70828114/e0f1455c-b5ec-4c7c-8d0f-a683c3d9eaea)
![Image](https://github.com/hummingbot/gateway/assets/70828114/5073aafd-4a46-407a-a35e-b95961eb180c)
![Image](https://github.com/hummingbot/gateway/assets/70828114/19086c92-8701-43fc-8d07-36e0e16f0875)

# steps done for debugging

I deleted the conf/lists folder  from "gateway_files"

Run docker stop gateway && docker rm gateway

refactored the gateway-create.sh

prompt_copy_lists () {
  echo
  read -p "Do you want to generate default token lists? [Y/N] >>> " PROCEED
  if [[ "$PROCEED" == "Y" || "$PROCEED" == "y" ]]; then
    if [[ ! -d "$CONF_FOLDER/lists" || ! "$(ls -A $CONF_FOLDER/lists)" ]]; then
      mkdir -p "$CONF_FOLDER/lists"
      sudo chmod a+rw "$CONF_FOLDER/lists"
      docker cp "$INSTANCE_NAME:/home/gateway/src/templates/lists/." "$CONF_FOLDER/lists/"
      echo "Token list files successfully copied to $CONF_FOLDER/lists."
      # Proceed with your other tasks or functions as needed.
    else
      echo "Using existing token list files in $CONF_FOLDER/lists."
      # Proceed with your other tasks or functions as needed.
    fi
  elif [[ "$PROCEED" == "N" || "$PROCEED" == "n" ]]; then
    if [[ ! -d "$CONF_FOLDER/lists" || ! "$(ls -A $CONF_FOLDER/lists)" ]]; then
      echo "Error: Token list files not found in $CONF_FOLDER/lists."
      echo "Please make sure you generate default token lists or provide the necessary files manually."
      # You can choose to exit the script here or take any other appropriate action.
      # Example: exit 1
    else
      echo "Using existing token list files in $CONF_FOLDER/lists."
      # Proceed with your other tasks or functions as needed.
    fi
  else
    echo "Invalid input. Please enter 'Y' or 'N'."
    # You can choose to exit the script here or take any other appropriate action.
    # Example: exit 1
  fi
}


Enter Gateway version you want to use [latest/latest-arm] ✅
Enter a name for your new Gateway instance (default = "gateway") ✅
Enter the folder name where your Gateway files will be saved (default = "xxx_files") ✅
Enter the passphrase you used to generate certificates in Hummingbot ✅
Do you want to proceed with installation? Y
Created gateway successfully
Do you want to generate certs from a Hummingbot instance? Y ✅
Enter the path to the folder where Hummingbot certificates are stored ✅
Do you want to generate default token lists? [Y/N] selected N
 response Token list files not found in /home/lee/hummingbot_files/conf/lists.
      Please make sure you generate default token lists or provide the necessary files manually.

which is not expected

i.e for any answer provided while generating it, it stills generate could you rebuild the image and send screenshots from your instance

**Comment by fengtality** [comment]
This may have been fixed by https://github.com/hummingbot/gateway/pull/160. @rapcmia can you check?

**Comment by isreallee82** [comment]
Alright @fengtality

**Comment by rapcmia** [comment]
@fengtality @isreallee82 
Yes, PR160 fix issues on docker build. This bounty is safe to close.
