### ISSUE TITLE
Auto-copy token lists into `/conf/lists`

### ISSUE THREAD

**Issue by fengtality** [hummingbot/gateway#148]
## Description

* In the last release, token lists were moved into the `/conf/lists` directory, allowing users to edit token lists for each chain
* They are not copied by default, which is why Docker users have to run a separate `docker cp...` command
* Since the config `.yml` files are copied by default into `/conf` , this should be possible for the lists as well
* Take over this PR: https://github.com/hummingbot/gateway/pull/146

## Bounty

* Sponsor: Hummingbot Foundation
* Budget: [HGP-26](https://snapshot.org/#/hbot.eth/proposal/0x7a02f532e0452d3ce7f8b64a8a52e6bed285cc65461a1523fa0f91f2024f8c01)
* Classification: P3
* Bounty: 10,000 HBOT
* Developer share: 100% - paid upon merge to development
* Status: Assigned to @vic-en since he has experience with Gateway codebase

**Comment by fengtality** [comment]
@carlitogetaladajr please schedule this bounty for payout - thanks!

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to Vic-en . The PR has been deployed on development branch and 
 hummingbot version 1.18.0.
