### ISSUE TITLE
gateway-network/config failed and unhandled error

### ISSUE THREAD

**Issue by whitechiken** [hummingbot/gateway#167]
unable to connect to etheruem network

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:Deploy Hummingbot and Gateway Instances in the hummingbot _gateway_compose file using wsl ubuntu

Here are the steps to reproduce the issue (see attachments in the section below):
1. install wsl ubuntu and docker desktop
2. follow the step from the readme in the hummingbot _gateway_compose file
3 gateway connect uniswap and then get error

// If applicable, add screenshots to help explain your problem.

**Release version**-=1. 17. 0

file etheruem.yml docker-compose.yml

[raphael@Raph3_ ~_deploy-examples_hummingbot_gateway_compose 2023-07-20 5_26_33 PM](https://github.com/hummingbot/gateway/assets/140143794/c95c99c9-7d67-41d2-b96d-4ed618b03082)

**Optional: your discord username:whitechiken

**Comment by fengtality** [comment]
Looks like it's calling the old `/network/config` routes that were changed in v1.18.0 by this PR: https://github.com/hummingbot/gateway/pull/147

I suggest deleting your old images with `docker image rm` and running it again using the `latest` (v1.18) and `main` images.

**Comment by rapcmia** [comment]
I am able to reproduce on version 1.17 and updated to 1.18 fixed the issue. Please update or use a fresh installation of version 1.18.0 thank you

Screenshot of issue:
![image](https://github.com/hummingbot/gateway/assets/73840223/645bc70d-4e3a-4bd7-8310-2b7e504dd5f1)
