### ISSUE TITLE
Dexalot - EUROC and sAVAX balances are not recognized 

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/gateway#232]
**Describe the bug**
EUROC and sAVAX are not being recognized on Dexalot exchange when used. Tried to add these to the gateway connector-token command but still no go. 

On the screenshot below, ran balance command and observed only few of the added tokens are showing available yet on exchange it has balance. The tokens sAVAX and EUROC are also updated on `avalanche_tokens.json`
![image](https://github.com/hummingbot/gateway/assets/73840223/bd9446d9-ee78-4591-8810-5bfc074cf5f4)

When starting the strategy using DEX connector, it is expected to display the balances for the market pair but no avail
- This causes the exchange to only submit order on buy which at the time it was running, it has enough balance to open a sell order 
![image](https://github.com/hummingbot/gateway/assets/73840223/41acda4f-df51-4a87-8575-9b72c4a4f219)
![image](https://github.com/hummingbot/gateway/assets/73840223/67018f82-c495-4559-b3a4-6c85ff14f71a)

**Steps To Reproduce**
- Setup client and gateway 
- Setup dexalot wallet then check balances by:
  - Using gateway balance command 
  - Using gateway connector-tokens
  - Setup PMM then start, observe the prompt for balances

**Release version**
dev-1.22.0

[logs_dexalot-eurocusdc.log](https://github.com/hummingbot/gateway/files/13344666/logs_dexalot-eurocusdc.log)

**Comment by fengtality** [comment]
My guess is this check in https://github.com/hummingbot/gateway/blob/main/src/connectors/dexalot/dexalot.ts#L136
 is the issue: 
```
    const balances = await Promise.all(
      req.tokenSymbols.map((symbol) => {
        return this._portfolioContract.getBalance(
          req.address,
          fromUtf8(symbol)
        );
      })
    );
```

**Comment by rapcmia** [comment]
Fix applied to development branch.
