### ISSUE TITLE
Gateway - "gateway connector-tokens" command does not display any balance for connectors that support LP

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/gateway#248]
**Describe the bug**
Add wallet for uniswaplp and run `gateway connector-tokens` then hit tab to check connectors to use

![image](https://github.com/hummingbot/gateway/assets/73840223/aa01d76b-a812-4755-885c-1aee1278c8d0)

Observed that it does not let us select other connectors that support LP. Please be advised that `pancakeswapLP` is still in development phase and not available yet on latest development branch 🙇🏼 

**Steps To Reproduce**
1. Setup uniswaplp then run "gateway balance" command to check if successful
2. Run `gateway connector-tokens ...` then hit tab to select connector specifically uniswapLP

**Release version**
1.22.0 and dev-1.23.0

**Comment by isreallee82** [comment]
but @rapcmia since gateway connector-tokens now uses only chain_network this wont report tokens separately for connectors that support LP
