### ISSUE TITLE
Gateway - Failed to yarn start when `passhrase is numerical` (property must be of type string)

### ISSUE THREAD

**Issue by nikspz** [hummingbot/gateway#26]
Gateway - Failed to yarn --start when passhrase is numerical 

Steps:
1. `git clone -b development https://github.com/hummingbot/hummingbot.git development`
2. install, compile and start the bot
3. for gateway generate-certs use `numbers as passphrase` (1234)
4. open another terminal and clone gateway `git clone -b development https://github.com/hummingbot/gateway gateway`
5. cd gateway && yarn && yarn build
6. ./gateway-setup.sh
7. yarn start  --passphrase=1234

Actual:
Bot returns error and Failed to start
error |   Failed to start the server with https. Confirm that the SSL certificate files exist and are correct. Error: TypeError [ERR_INVALID_ARG_TYPE]: `The "options.passphrase" property must be of type string`. Received type number (1234)

Expected: 
Bot is able to start when passphrase is numbers

![image](https://user-images.githubusercontent.com/83953535/219584356-b1ea831a-a4de-4b2e-abaa-cd5889316a4d.png)

FYI: Issue was previously fixed here for gateway in hummingbot repo:  https://github.com/hummingbot/hummingbot/pull/6067

**Comment by fengtality** [comment]
Fixed by #23
