### ISSUE TITLE
CAN I GET SOME HELP PLEASE

### ISSUE THREAD

**Issue by RFARREY** [hummingbot/gateway#267]
![Screenshot 2024-01-17 131537](https://github.com/hummingbot/gateway/assets/45320379/68bda1a4-1dbf-4f4a-9b7f-25c70d865971)

I am installing Gateway and these errors pop up. Am I missing anything? Kindly assist. Thanks

**Comment by nikspz** [comment]
hi @RFARREY I think you're using windows machine, 
You should use WSL for the correct installation steps:

https://hummingbot.org/installation/windows/
https://hummingbot.org/gateway/installation/

**Comment by nikspz** [comment]
Also you could check this youtube video (this one is for docker installation)
https://www.youtube.com/watch?v=D05kKp-f2vg

**Comment by RFARREY** [comment]
No I am using Ubuntu . WSL

**Comment by RFARREY** [comment]
Lol. Yeah you're right. This is embarrassing. I was using Windows.

**Comment by nikspz** [comment]
If you still have questions/troubles after checking videos and docs please proceed in discord #support channel
https://discord.gg/zMVax3NR
