### ISSUE TITLE
Failed to create multiple containers with same tag using ./gateway-create.sh (error `container version latest already exist` and Aborting creation)

### ISSUE THREAD

**Issue by nikspz** [hummingbot/gateway#27]
Bot fails to create another container with ./gateway-create.sh (if it using same tag)

before (1.12 master): image:container1, image:container2
now: image:container1, image:container2(not possible)

Steps to reproduce:
1. Clone and install bot development branch
2. create and set up one container using ./gateway-create.sh (with latest tag)
3. make sure that container with latest tag created
4. try to create another container using ./gateway-create.sh and default tag (latest)

Actual:
User failed to create second/another container using ./gateway-create.sh 
Bot returns an error and Aborting creation
`container version latest already exist, Remove existing container before creating new one`

Expected: 
Users should be able to create multiple docker containers using script

![image](https://user-images.githubusercontent.com/83953535/219588680-a33380c3-f202-4e18-a051-3eb8e0c6b65d.png)

**Comment by nikspz** [comment]
Fede pushed a fix to the `main` branch, seems fixed. ✅

Should push the fix on `development` ⬅

![image](https://user-images.githubusercontent.com/83953535/220268686-60032b5d-69fb-43b6-a853-3e466d3ff9bf.png)

**Comment by nikspz** [comment]
User able to create multiple containers now, but 

1. Failed to create with docker gw the `development` tag if another gw docker with same  development tag running
![multiple instances of gateway - failed to create docker gw when another gateway is running](https://user-images.githubusercontent.com/83953535/220416018-97a8eef2-a30e-4ae5-a99d-1a23416bede5.gif)

2. Failed to start 2 instances simultaneously (for example if you want to run pangolin on one and traderjoe on another) 
https://www.loom.com/share/bc404a6aee5648e181a97ff16a9380af

**Comment by fengtality** [comment]
Fixed by https://github.com/hummingbot/gateway/pull/38
