### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by cxfshelter** [hummingbot/gateway#291]
**Describe the bug**
// A clear and concise description of what the bug is.
nodejs = v16.0.0
The environment is configured according to https://hummingbot.org/gateway/installation/#run-setup-script and this error is reported when entering a command: $ yarn start --passphrase=xxxxxx. How to solve it?

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://github.com/hummingbot/gateway/assets/4158369/85972a8a-910e-4391-87d2-938fc7ad394b)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
v1.25.0

**Attachments**
// It is important that you attach the required files for us to be able to investigate the issue. 
// Please attach the chain.yml file from your gateway "conf" folder, e.g ethereum.yml
don't have conf file

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

Sorry, I'm new to this

**Comment by rapcmia** [comment]
Hi @cxfshelter thanks for reporting this issue, please try node version v18 or higher. Our team will update the docs 🙇🏼

**Comment by cxfshelter** [comment]
> Hi @cxfshelter thanks for reporting this issue, please try node version v18 or higher. Our team will update the docs 🙇🏼

ok, thanks
