### ISSUE TITLE
Add `poolID` to Gateway AMM endpoints

### ISSUE THREAD

**Issue by fengtality** [hummingbot/gateway#302]
## Why

AMM designs are getting more complex, and a simple QUOTE/BASE tuple may match multiple pools in protocols like Balancer. Similarly, other AMMs feature different fee settings for the same QUOTE/BASE pool. To allow users to specify which pools they are trading against, we need to specify the pool ID instead of these simple descriptors. 

## What
Add `poolID` as an optional parameter to the following Gateway endpoints below. Initially, the parameter is only required by AMMs like Balancer. For these AMMs, `poolID` should be used to fetch the right pool, not the other variables.

```
/amm/price
/amm/trade
/amm/liquidity/price
/amm/liquidity/add
```

Afterwards, add error-handling logic to inform users when `poolID` is missing, as well as unit tests.

## Bounty
* Sponsor: Hummingbot Foundation
* Funding: Ethereum pot - see Connector Pots tab in [HBOT Tracker](https://docs.google.com/spreadsheets/d/1UNAumPMnXfsghAAXrfKkPGRH9QlC8k7Cu1FGQVL1t0M/edit?usp=sharing) 
* Bounty amount: 500 USD or 167,000 HBOT (0.003 current price)
* Developer portion: 100%
* Status: OPEN

**Comment by vic-en** [comment]
I can work on this.

**Comment by vic-en** [comment]
You can assign to @webbdays he/she is really interested and can get it done.

**Comment by webbdays** [comment]
Thanks @vic-en

**Comment by webbdays** [comment]
I will ask here if i have any doubts in between.
Thank you.

**Comment by webbdays** [comment]
Hi @fengtality, @nikspz
I have made an initial commit, which allows the user to pass poolID as req parameter.
If user dont pass it then error message will be sent in response.
But i don't have the domain knowledge on how to use the poolID further in the codebase.
Please help.
Thanks.

**Comment by vic-en** [comment]
> Hi [@fengtality](https://github.com/fengtality), [@nikspz](https://github.com/nikspz) I have made an initial commit, which allows the user to pass poolID as req parameter. If user don't pass it then error message will be sent in response. But i don't have the domain knowledge on how to use the poolID further in the codebase. Please guide. Thanks.

I can give you some hints to help you get it done but I expect you to have an understanding of how to interract with smart contracts at the very least. Do you?

**Comment by webbdays** [comment]
I have some knowledge, previously used web3.js while i was learning to build a smart contract with local blockchain network using Ganache.
I have to revisit the concepts related to that.
I can understand what's happening with codebase with some guidance/help.

**Comment by nikspz** [comment]
@webbdays Please be informed: Team shouldn't have to "hand hold" a dev through the process

**Comment by webbdays** [comment]
I am currently going through the code and docs. I will try mybest.
Thanks.

**Comment by nikspz** [comment]
hi @webbdays, upon discussion with the team we should assign this bounty to vic-en. 

You could check one of the bounties here and leave comment if you want to be assigned:
https://github.com/hummingbot/hummingbot/issues/6914
https://github.com/hummingbot/hummingbot/issues/6898
https://github.com/hummingbot/hummingbot/issues/6899

**Comment by nikspz** [comment]
#302 Assigned to @vic-en, please be informed:
- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Please review and follow contribution guidelines (https://hummingbot.org/developers/contributions/)
- Please review the checklist after PR submitted (https://hummingbot.org/developers/contributions/#checklist)
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by webbdays** [comment]
ok.

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @vic-en . The fix has been deployed on development branch and hummingbot version 1.27.0.
