### ISSUE TITLE
Gateway install from source offline

### ISSUE THREAD

**Issue by okori-d** [hummingbot/gateway#351]
The gateway doesn't link to hummingbot client when you install and run it(gateway) from source.

**Comment by okori-d** [comment]
**Fix**: install both gateway and hummingbot from source inorder to be able to link gateway(from source) to the client. Client will need some extra configs to run smoothly.

**Comment by sdyanglei** [comment]
Could you please share what extra configurations are needed? I’m facing the same issue and haven’t been able to resolve it. Thank you!
