### ISSUE TITLE
Unknown IP Address on gateway connected to

### ISSUE THREAD

**Issue by delgemoon** [hummingbot/gateway#368]
I am seeing the gateway connected to this ip address - **72.46.86.254**. But I counld not find any information about this ip. I am guessing polygon lap. But I have not been making any request related to polygon network. 

So anyone here can help to me understand why the gateway need to connect to this ip.

thanks
Tam

**Comment by rapcmia** [comment]
Hi @delgemoon thanks for reporting however i dont recall pointing to specific ip address for gateway specially the one provided on this ticket. Also we would appreciate if you would follow the template upon opening the [bug report](https://github.com/hummingbot/gateway/issues/new/choose) else we can't reproduce the issue reported here. 

If you still need us to investigate, kindly reopen with supporting files and steps to reproduce. Thank you
