### ISSUE TITLE
Can't decrypt SSL certs

### ISSUE THREAD

**Issue by fengtality** [hummingbot/gateway#43]
**Describe the bug**
// A clear and concise description of what the bug is.

A Botcamp student reported that they are unable to start Gateway b/c of a decryption issue

**Steps To Reproduce**
- User is on Ubuntu 22.04.2 LTS, on VirtualBox / Windows 10.
- User installed Gateway from source
- 
![image-1](https://user-images.githubusercontent.com/1795030/221367446-f847194d-2570-49b5-9212-af26dd2ac04b.png)

![image](https://user-images.githubusercontent.com/1795030/221367350-10f91db4-7d63-4d99-aafe-0620484a6973.png)

The error shown seems to indicate that the cert files are present, but Gateway is unable to decrypt them.

QA: Please try to replicate this issue.

**Comment by rapcmia** [comment]
Update: 
Tested both Client and Gateway using development branch
- Created a test server on AWS Ubuntu22.04 and connection between source client and source gateway
- Setup gateway connection: ok  
   ![image](https://user-images.githubusercontent.com/73840223/221552954-fe538576-377d-410a-b754-66ab804cd7ee.png)
- Ran `gateway generate-certs` again and copied the updated certs file using `gateway-setup.sh` on gateway 
   - Run `yarn start --passphrase=<new passphrase>` still works as expected
- Tried different scenarios no reproduce issue:
   - Run yarn start without copying the certs from client > no go
   - Run yarn start with numerical password > still works as expected
   - The closest we can have a `bad decrypt` error is when running yarn start with incorrect passphrase
      ![image](https://user-images.githubusercontent.com/73840223/221554430-13215bb4-7953-4295-ae66-fdcac4595b11.png)

**Comment by rapcmia** [comment]
Update:
Managed to reproduce the issue using WSL ubuntu20.04 and can confirm this is related to incorrect passphrase
![image](https://user-images.githubusercontent.com/73840223/221767351-9a308795-9083-4f70-87aa-aa7bc611eb92.png)
