### ISSUE TITLE
UniswapLP Polygon mainnet - 'Token not supported' error

### ISSUE THREAD

**Issue by fengtality** [hummingbot/gateway#44]
Original issue: https://github.com/hummingbot/hummingbot/issues/6099

--
Whatever I do on Polygon, I always get "Token not supported"

Steps to reproduce:

Created clean docker instance
Created gateway with 'gateway create'
Set up uniswap and uniswapLP with appropriate information and keys
Created strategy with uni_v3_lp on pair WMATIC-USDC
"start"
Release: latest / 1.12.0

log snippet:

...
2023-02-20 01:23:45 | error | Token not supported: WMATIC | Error: Token not supported: WMATIC
at getFullTokenFromSymbol (/usr/src/app/dist/src/connectors/uniswap/uniswap.controllers.js:303:15)
at /usr/src/app/dist/src/connectors/uniswap/uniswap.controllers.js:278:24
at Generator.next ()
at /usr/src/app/dist/src/connectors/uniswap/uniswap.controllers.js:8:71
at new Promise ()
at __awaiter (/usr/src/app/dist/src/connectors/uniswap/uniswap.controllers.js:4:12)
at poolPrice (/usr/src/app/dist/src/connectors/uniswap/uniswap.controllers.js:276:12)
at /usr/src/app/dist/src/amm/amm.controllers.js:79:52
at Generator.next ()
at fulfilled (/usr/src/app/dist/src/amm/amm.controllers.js:5:58)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by fengtality** [comment]
While `gateway create` is now deprecated, the error message above seems to indicate that Hummingbot could not resolve the WMATIC symbol.

I confirmed that Gateway can resolve the WMATIC symbol via Postman:
<img width="1245" alt="Screen Shot 2023-02-25 at 8 22 27 AM" src="https://user-images.githubusercontent.com/1795030/221367943-7f8b4891-5ca8-4f8d-8cf9-8b559face1a4.png">. 

I'll check if this works in Hummingbot later.

**Comment by nikspz** [comment]
Latest development 1.14.0 Issue reproduced 
![image](https://user-images.githubusercontent.com/83953535/223093984-fb2dd921-0755-4f98-8eae-c60bc0e024c8.png)

Noticed that on uniswap WMATIC token will be placed as MATIC-USDC
![WMATIC-USDC turned into MATIC-USDC when creating a pool](https://user-images.githubusercontent.com/83953535/223093690-4a33924d-04f1-420e-a447-d0be10d50f37.gif)

Also noticed that bot mentioned WETH-USDC as the non-active market for uniswapLP-polygon-mainnet
However this market exists on the exchange
![image](https://user-images.githubusercontent.com/83953535/223094826-d6a34e93-9648-449b-8eaa-d7ccef7d88af.png)

**Comment by nikspz** [comment]
Same issue (Token not supported) testing other pairs (UNI-USDC)
![image](https://user-images.githubusercontent.com/83953535/223097237-b07f13c8-bab8-450c-91a9-4283aa648ef7.png)

**Comment by fengtality** [comment]
@nikspz Can you still reproduce this issue?

**Comment by johna1203** [comment]
I think UniswapLP does not support Polygon yet. I was looking at the code, and it seems that UniswapLP is not handling the 'Polygon' chain.

https://github.com/hummingbot/gateway/blob/main/src/connectors/uniswap/uniswap.lp.helper.ts#L38


You can notice that in uniswap.ts, it is being checked if it's Ethereum; otherwise, it will be Polygon.

https://github.com/hummingbot/gateway/blob/main/src/connectors/uniswap/uniswap.ts#L61

I'm trying to fix this, but I think I'll spend some time testing to make sure everything is running smoothly.
