### ISSUE TITLE
Injective protocol - Balance command does not display the correct values

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/gateway#70]
**Describe the bug**
While testing a PR we noticed that the balance for Injective does not display the correct values. This makes the client not able to create orders due to insufficient balances

_Note: Same wallet has been used for testing before and still got the assets available_

Development client
![image](https://user-images.githubusercontent.com/73840223/226341900-7adecb0a-08cb-4b8f-a8ae-c8716607413b.png)

![image](https://user-images.githubusercontent.com/73840223/226342736-29535cbd-0e25-4b51-93c9-c0fb7ff5ed15.png)

Exchange account - https://helixapp.com/account
![image](https://user-images.githubusercontent.com/73840223/226341988-3b11e4a1-84b9-4304-bc7e-1c2de6ed9c3e.png)

**Steps To Reproduce**
1. Connect Injective wallet
2. Run balance command 
3. Setup simple PMM and observe client behavior

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
Gateway development branch

**Attachments**
// It is important that you attach the required files for us to be able to investigate the issue. 
// Please attach the chain.yml file from your gateway "conf" folder, e.g ethereum.yml
No config available, all settings are on default

**Comment by nikspz** [comment]
Fixed with https://github.com/hummingbot/hummingbot/pull/6168
