### ISSUE TITLE
Injective protocol - No active order displayed and unable to cancel orders

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/gateway#73]
**Describe the bug**
We can confirm that issue on wallet has been fix on https://github.com/hummingbot/hummingbot/pull/6168 however when we tried to setup a simple PMM strategy, the client was able to create orders but at the same time getting `order {order_id} has failed` resulting to no active orders displayed. Crosschecking the Injective protocol website and confirmed orders are active.

![image](https://user-images.githubusercontent.com/73840223/227839084-4d5acabd-72f7-4b8c-aabf-6dbde9d5076e.png)

It is also observed that it will not let us cancel the orders from the client resulting to:
- Orders stuck on exchange
- Docker logs shows DELETE endpoint submitted but orders are not removed (waited for 3-5mins, refreshed website)
- Balance command displays allocated assets

![image](https://user-images.githubusercontent.com/73840223/227840569-0ca52d09-3675-4f05-8499-c9f309a95c31.png)

![image](https://user-images.githubusercontent.com/73840223/227840082-1ef5fe07-109c-43c8-89b2-ab5acbd8e5eb.png)

**Steps To Reproduce**
1. Setup client and gateway development branch
2. Setup simple PMM and observe client / gateway behavior 

**Release version**
dev-1.14.0
gateway development branch

**Attachments**
// It is important that you attach the required files for us to be able to investigate the issue. 
// Please attach the chain.yml file from your gateway "conf" folder, e.g ethereum.yml

[Injective protocol.zip](https://github.com/hummingbot/gateway/files/11074582/Injective.protocol.zip)

**Comment by keithbaum** [comment]
This may be related to how order hash is calculated. Code changes in the hummingbot api_data_source did not change place_order logic, but maybe this is related to the update of the pyinjective lib. Need to investigate on that side, probably not related to gateway
